apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "1234" # Base64 encoding for "1234"
  MYSQL_USER: "app_user" # Base64 encoding for "app_user"
  MYSQL_PASSWORD: "1234" # Base64 encoding for "1234"