apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  SECRET_KEY: dummy-secret
  DB_NAME: app_db
  DB_USER: app_user
  DB_PASSWORD: "1234"
  DB_HOST: mysql.mysql.svc.cluster.local
